on:
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm ci
      - run: npm test
      - name: Collect coverage from client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: client